"project_id": "797530"
"api_token": "5e165be5744ec99d424e108afa9d49f26c4e3f4d28dd6ba7f515a5eb8a7c55dedf93208a9c0da0b0"
"base_path": "."
"base_url": "https://api.crowdin.com"

"files": [
  {
    "source": "/locales/en/**/*.json",
    "translation": "/locales/%two_letters_code%/**/%original_file_name%",
    "type": "json"
  }
]
