name: Crowdin Translation Sync

on:
  push:
    branches:
      - main

permissions:
  contents: write  # opcional, mas deixa explícito

jobs:
  sync-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Crowdin Action
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          download_translations: true
          create_pull_request: true
          pull_request_title: 'chore: update translations from Crowdin'
          localization_branch_name: 'crowdin-translations'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}   # usa o PAT aqui no lugar do GITHUB_TOKEN padrão
