name: Crowdin Sync

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: crowdin/github-action@v2.3.0
        with:
          upload_sources: true
          download_translations: true
          create_pull_request: true
          pull_request_title: 'chore: update translations from Crowdin'
          localization_branch_name: 'crowdin-translations'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

